### ISSUE TITLE
Can you add a compatibility layer for the Vue composition API?

### ISSUE THREAD

**Issue by matthew-dean** [OSSPhilippines/vue-footprints#1]
It would be nice to do this instead of registering a global:
```vue
<script setup lang="ts">
import { useFootprints } from 'vue-footprints'

const footprints = useFootprints();
</script>
```
Vue-Router has a similar pattern

**Comment by matthew-dean** [comment]
This worked for me:
```ts
import { computed, type ComputedRef } from 'vue'
import { useRoute } from 'vue-router'
import startCase from 'lodash/startCase'

const route = useRoute()
const getComputed = () => route.matched?.map(r => {
  let footprint = (r.meta?.footprint ?? '') as string

  if (!footprint) {
    if (typeof route.name === 'string') {
      footprint = startCase(route.name).replace(/[A-Z]/g, ' $1').trim()
    } else {
      return false
    }
  }

  const active = route.name === r.name
  const returnRoute = { name: r.name, path: r.path, meta: r.meta }

  return {
    footprint,
    active,
    route: returnRoute
  }
}).filter(r => r)

const breadcrumbs = computed(getComputed) as ComputedRef<Exclude<ReturnType<typeof getComputed>[0], false>[]>
```

**Comment by jofftiquez** [comment]
> It would be nice to do this instead of registering a global:
> 
> ```
> <script setup lang="ts">
> import { useFootprints } from 'vue-footprints'
> 
> const footprints = useFootprints();
> </script>
> ```
> 
> Vue-Router has a similar pattern

Hi, this would be a great idea. Let's do it. I'll implement this after the holidays, thank you!

**Comment by jofftiquez** [comment]
Hi @matthew-dean kindly check the new major version `@ossph/vue-footprints` `v2.0.0`. Also you can check this new release notes: https://github.com/OSSPhilippines/vue-footprints/releases/tag/v2.0.0 

Let me know if these works for your needs.
